/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    ACol: typeof import('ant-design-vue/es')['Col']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ARow: typeof import('ant-design-vue/es')['Row']
    MButton: typeof import('./src/components/button/m-button.vue')['default']
    MContent: typeof import('./src/components/layout/m-content.vue')['default']
    MFooter: typeof import('./src/components/layout/m-footer.vue')['default']
    MHeader: typeof import('./src/components/layout/m-header.vue')['default']
    MLayout: typeof import('./src/components/layout/m-layout.vue')['default']
    MSider: typeof import('./src/components/layout/m-sider.vue')['default']
    PageHeader: typeof import('./src/components/page-header/page-header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
